version: '3.8'

services:
  kooder:
    image: hub.gitee.cc/kooder/kooder:202103
    container_name: kooder
    volumes:
      - ./core/src/main/resources/kooder.properties:/root/core/src/main/resources/kooder.properties:ro
    ports:
      - 8080:8080