version: '3.8'

services:
  koodera:
    image: registry.cn-hangzhou.aliyuncs.com/devops_hu/kooder:202103
    expose:
      - 8080
  kooderb:
    image: registry.cn-hangzhou.aliyuncs.com/devops_hu/kooder:202103
    expose:
      - 8080

  haproxy:
    image: haproxy:1.6
    volumes:
      - ./core/src/main/resources/kooder.properties:/root/core/src/main/resources/kooder.properties:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - koodera
      - kooderb
    ports:
      - "8080:8080"



